### ISSUE TITLE
java file missing

### ISSUE THREAD

**Issue by bhagatabhijeet123** [SankarBalaji/Remainder#1]
hello sankar sir, OnAlarmReceiver.class is not found, please upload it

**Comment by SankarBalaji** [comment]
Hi Bhagat, 
      Really sorry about partial update. This project was dropped due to lack of time and interest. By the time i decided to quit the project lot of apps with the same idea cam up. What ever I have developed, I have uploaded  and lost the other backups. Sorry bhagat I am not able to support you further.

**Comment by bhagatabhijeet123** [comment]
ok, no problem, i will find another one, bye the way i am developing
android app and wanted to launch in this month, any tip about digital
marketing will help me, thank you
